# Generated by Django 4.0.5 on 2022-07-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='laguage',
            new_name='language',
        ),
    ]
